# Generated by Django 5.1.1 on 2024-12-04 18:17

import api.mixins
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'The description must contain at least 3 characters')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(12, 'The description must contain at least 12 characters')])),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            bases=(models.Model, api.mixins.DueDateValidationMixin),
        ),
    ]
